name: Deploy naar SmarterASP 

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Haal de code op uit de repo
    - name: ğŸšš Code Ophalen
      uses: actions/checkout@v3

    # 2. Installeer .NET op de GitHub server
    - name: ğŸ› ï¸ Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Pas dit aan als jullie .NET 6 of 7 gebruiken
      # 2.5 Vervang de placeholder door het echte geheim
    - name: ğŸ” Connection String instellen
      uses: microsoft/variable-substitution@v1
      with:
        files: 'appsettings.json'
      env:
        ConnectionStrings.DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
    # 3. Bouw de website (Compileren)
    - name: ğŸ—ï¸ Bouwen en Publiceren
      run: dotnet publish "Central Sports.csproj" -c Release -o ./publish_output --self-contained true -r win-x64


    # 4. Uploaden naar SmarterASP via FTP
    - name: ğŸ“‚ Uploaden naar FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish_output/

        server-dir: /site1/  
